PythonWeb/PythonWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("my-admin/user/", include("user.urls")),
    path("api/user/", include("user.urls_api")),

    path('api/token/',
         jwt_views.TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('api/token/refresh/',
         jwt_views.TokenRefreshView.as_view(),
         name='token_refresh'),
    path('', include('app.urls')),
]

PythonWeb/app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('hello/', views.HelloView.as_view(), name='hello'),
]

PythonWeb/user/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from user import views_api, views
from django.conf.urls import url

urlpatterns = [
    # path('basic/', views_api.API_objects.as_view()),
    # path('basic/<int:pk>/', views_api.API_objects_details.as_view()),
    path('show', views.show),
    path('add', views.add),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.delete),

    # # url(
    # #     r'^api/v03/view/$',
    # #     views_api.get_post_employee,
    # #     name='get_post_employee'
    # # ),
    #
    # url(
    #     r'^api/v01/user',
    #     views_api.get_all,
    #     name='get_all_user'
    # ),
    # url(
    #     r'^api/v01/user/add/$',
    #     views_api.add,
    #     name='add_user'
    # ),
    # # url(
    # #     r'^api/v01/user/edit/(?P<pk>[0-9]+)$',
    # #     views_api.get_edit,
    # #     name='get_edit_user'
    # # ),
    # path('api/v01/user/edit/<int:id>',views_api.get_update_edit),
    # # url(
    # #     r'^api/v01/user/update',
    # #     views_api.update,
    # #     name='get_all_user'
    # # ),
    # #
    # # url(
    # #     r'^api/v01/user/delete/(?P<pk>[0-9]+)$',
    # #     views_api.deleteById,
    # #     name='delete_user'
    # # ),
    #
    # url(
    #     r'^api/v02/user/(?P<pk>[0-9]+)$',
    #     views_api.get_delete_update_employee,
    #     name='get_delete_update_employee'
    # ),
    # url(
    #     r'^api/v02/user/$',
    #     views_api.get_post_employee,
    #     name='get_post_employee'
    # )
]
urlpatterns = format_suffix_patterns(urlpatterns)

PythonWeb/app/models.py
from django.db import models

# Create your models here.

PythonWeb/user/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    uid = models.CharField(max_length=20)
    uname = models.CharField(max_length=100)
    uemail = models.EmailField()
    ucontact = models.CharField(max_length=15)
    upassword = models.CharField(max_length=20)
    # isActive = models.CharField(max_length=1)

    class Meta:
        db_table = "user"

PythonWeb/app/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated


class HelloView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        content = {'message': 'Hello, GeeksforGeeks'}
        return Response(content)

PythonWeb/hello/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def home(request):
    return HttpResponse("Hello, Django!")

PythonWeb/user/views.py
from django.shortcuts import render, redirect
from user.form import UserForm
from user.models import User


# Create your views here.
def show(requsest):
    users = User.objects.all();
    return render(requsest, 'show.html', {'users': users})


def add(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/my-admin/user/show')
            except:
                pass
    else:
        form = UserForm()

    return render(request, 'index.html', {'form': form})


def edit(request, id):
    user = User.objects.get(id=id)
    return render(request, 'edit.html', {'user': user})


def update(request, id):
    user = User.objects.get(id=id)
    form = UserForm(request.POST, instance=user)
    if form.is_valid():
        form.save()
        return redirect("/my-admin/user/show")
    return render(request, 'edit.html', {'user': user})


def delete(request, id):
    user = User.objects.get(id=id)
    user.delete()
    return redirect("/my-admin/user/show")

PythonWeb/user/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<form method="POST" class="post-form" action="/my-admin/user/update/{{ user.id }}">
    {% csrf_token %}
    <input type="hidden" name="upassword" id="id_upassword" required maxlength="20"
           value="{{ user.upassword }}"/>
    <div class="container">
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <h3>Update Details</h3>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">User Id:</label>
            <div class="col-sm-4">
                <input type="text" name="uid" id="id_uid" required maxlength="20" value="{{ user.uid }}"/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">User Name:</label>
            <div class="col-sm-4">
                <input type="text" name="uname" id="id_uname" required maxlength="100" value="{{ user.uname }}"/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">User Email:</label>
            <div class="col-sm-4">
                <input type="email" name="uemail" id="id_uemail" required maxlength="254"
                       value="{{ user.uemail }}"/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">User Contact:</label>
            <div class="col-sm-4">
                <input type="text" name="ucontact" id="id_ucontact" required maxlength="15"
                       value="{{ user.ucontact }}"/>
            </div>
        </div>

        {#        <div class="form-group row">#}
        {#            <label class="col-sm-2 col-form-label">User Password:</label>#}
        {#            <div class="col-sm-4">#}
        {#                <input type="text" name="upassword" id="id_upassword" required maxlength="15"#}
        {#                       value="{{ user.upassword }}"/>#}
        {#            </div>#}
        {#        </div>#}


        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>
    </div>
</form>
</body>
</html>

PythonWeb/user/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<form method="POST" class="post-form" action="/my-admin/user/add">
    {% csrf_token %}
{#    <input type="hidden" name="isActive" id="id_isActive" required maxlength="20" value="{{ user.isActive }}"/>#}
    <div class="container">
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <h3>Enter Details</h3>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">User Id:</label>
            <div class="col-sm-4">
                {{ form.uid }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">User Name:</label>
            <div class="col-sm-4">
                {{ form.uname }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">User Email:</label>
            <div class="col-sm-4">
                {{ form.uemail }}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">User Password:</label>
            <div class="col-sm-4">
                {{ form.upassword }}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">User Contact Phone Number:</label>
            <div class="col-sm-4">
                {{ form.ucontact }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</form>
</body>
</html>

PythonWeb/user/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Records</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>User ID</th>
        <th>User Name</th>
        <th>User Email</th>
        <th>User Contact</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr>
            <td>{{ user.uid }}</td>
            <td>{{ user.uname }}</td>
            <td>{{ user.uemail }}</td>
            <td>{{ user.ucontact }}</td>
            <td>
                <a type="button" class="btn btn-success" href="/my-admin/user/edit/{{ user.id }}">Edit</a>
                <a type="button" class="btn btn-danger" href="/my-admin/user/delete/{{ user.id }}">Delete</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/my-admin/user/add" class="btn btn-primary">Add New Record</a></center>
</body>
</html>